# Site settings
title: Hello world~
url: "http://yinheng.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  Hello, world.

# Your information
email: yinheng@life.com
author: Yinheng
avatar: "https://raw.githubusercontent.com/yinheng/yinheng.github.io/master/images/avatar2.jpg"
profile: ":sunglasses::smirk::see_no_evil::basketball:"
#twitter_username: twitter_username
github_username:  Yinheng

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator:  '<!-- more -->'
permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 8
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
